CREATE TYPE "mevki_tipi" AS ENUM (
  'kaleci',
  'savunmaci',
  'ortasaha',
  'forvet',
  'bilinmeyen'
);

CREATE TABLE "ulkeler" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kod" varchar(3) UNIQUE NOT NULL,
  "isim" varchar(100) NOT NULL,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "karsilasmalar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anahtar" varchar(50) UNIQUE NOT NULL,
  "isim" varchar(100) NOT NULL,
  "ulke_id" int,
  "ulusal_mi" boolean DEFAULT false,
  "uluslararasi_mi" boolean DEFAULT false,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "sezonlar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anahtar" varchar(20) UNIQUE NOT NULL,
  "baslangic_yili" smallint NOT NULL,
  "bitis_yili" smallint NOT NULL,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  CONSTRAINT "sezonlar_bitis_yili_chk" CHECK (bitis_yili = baslangic_yili + 1)
);

CREATE TABLE "takimlar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anahtar" varchar(50) UNIQUE NOT NULL,
  "isim" varchar(100) NOT NULL,
  "kisa_isim" varchar(50),
  "kurulus_yili" smallint,
  "ulke_id" int,
  "stadyum_id" int,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "stadyumlar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isim" varchar(100) NOT NULL,
  "kapasite" int,
  "sehir" varchar(100),
  "ulke_id" int,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "oyuncular" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isim" varchar(100) NOT NULL,
  "ilk_isim" varchar(50),
  "soyisim" varchar(50),
  "dogum_tarihi" date,
  "uyruk_id" int,
  "mevki" mevki_tipi DEFAULT 'bilinmeyen',
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "kadrolar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "takim_id" int,
  "oyuncu_id" int,
  "sezon_id" int,
  "forma_numarasi" smallint,
  "aktif_mi" boolean DEFAULT true,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "maclar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "yarisma_id" int,
  "sezon_id" int,
  "tur" smallint,
  "mac_tarihi" timestamp NOT NULL,
  "ev_sahibi_takim_id" int,
  "deplasman_takim_id" int,
  "stadyum_id" int,
  "ev_sahibi_goller" smallint DEFAULT 0,
  "deplasman_goller" smallint DEFAULT 0,
  "durum" varchar(20) DEFAULT 'planlandi',
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  CONSTRAINT "maclar_takimlar_farkli_chk" CHECK (ev_sahibi_takim_id != deplasman_takim_id)
);

CREATE TABLE "dizilisler" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mac_id" int,
  "takim_id" int,
  "oyuncu_id" int,
  "mevki" mevki_tipi,
  "ilk_onbir_mi" boolean DEFAULT true,
  "oynama_dakikasi" smallint DEFAULT 0,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "olaylar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mac_id" int,
  "oyuncu_id" int,
  "takim_id" int,
  "olay_tipi" varchar(20) NOT NULL,
  "dakika" smallint NOT NULL,
  "ayrinti" varchar(255),
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "istatistikler" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mac_id" int,
  "takim_id" int,
  "oyuncu_id" int,
  "goller" smallint DEFAULT 0,
  "asistler" smallint DEFAULT 0,
  "sari_kartlar" smallint DEFAULT 0,
  "kirmizi_kartlar" smallint DEFAULT 0,
  "topa_sahip_olma" decimal(5,2),
  "sutlar" smallint,
  "isabetli_sutlar" smallint,
  "tamamlanan_paslar" smallint,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "puan_durumu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "yarisma_id" int,
  "sezon_id" int,
  "takim_id" int,
  "sira" smallint,
  "oynanan" smallint DEFAULT 0,
  "galibiyet" smallint DEFAULT 0,
  "beraberlik" smallint DEFAULT 0,
  "maglubiyet" smallint DEFAULT 0,
  "atilan_goller" smallint DEFAULT 0,
  "yenilen_goller" smallint DEFAULT 0,
  "puan" smallint DEFAULT 0,
  "olusturulma_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "guncelleme_tarihi" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON COLUMN "maclar"."durum" IS 'CHECK (durum IN (''planlandi'', ''devam_ediyor'', ''bitti'', ''ertelendi''))';

COMMENT ON COLUMN "olaylar"."olay_tipi" IS 'CHECK (olay_tipi IN (''gol'', ''asist'', ''kart'', ''degisiklik''))';

ALTER TABLE "maclar"
  ADD CONSTRAINT "maclar_durum_chk"
  CHECK ("durum" IN ('planlandi', 'devam_ediyor', 'bitti', 'ertelendi'));

ALTER TABLE "olaylar"
  ADD CONSTRAINT "olaylar_olay_tipi_chk"
  CHECK ("olay_tipi" IN ('gol', 'asist', 'kart', 'degisiklik'));

ALTER TABLE "karsilasmalar" ADD FOREIGN KEY ("ulke_id") REFERENCES "ulkeler" ("id") ON DELETE SET NULL;

ALTER TABLE "takimlar" ADD FOREIGN KEY ("ulke_id") REFERENCES "ulkeler" ("id") ON DELETE SET NULL;

ALTER TABLE "takimlar" ADD FOREIGN KEY ("stadyum_id") REFERENCES "stadyumlar" ("id") ON DELETE SET NULL;

ALTER TABLE "stadyumlar" ADD FOREIGN KEY ("ulke_id") REFERENCES "ulkeler" ("id") ON DELETE SET NULL;

ALTER TABLE "oyuncular" ADD FOREIGN KEY ("uyruk_id") REFERENCES "ulkeler" ("id") ON DELETE SET NULL;

ALTER TABLE "kadrolar" ADD FOREIGN KEY ("takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;

ALTER TABLE "kadrolar" ADD FOREIGN KEY ("oyuncu_id") REFERENCES "oyuncular" ("id") ON DELETE CASCADE;

ALTER TABLE "kadrolar" ADD FOREIGN KEY ("sezon_id") REFERENCES "sezonlar" ("id") ON DELETE CASCADE;

ALTER TABLE "maclar" ADD FOREIGN KEY ("yarisma_id") REFERENCES "karsilasmalar" ("id") ON DELETE SET NULL;

ALTER TABLE "maclar" ADD FOREIGN KEY ("sezon_id") REFERENCES "sezonlar" ("id") ON DELETE CASCADE;

ALTER TABLE "maclar" ADD FOREIGN KEY ("ev_sahibi_takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;

ALTER TABLE "maclar" ADD FOREIGN KEY ("deplasman_takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;

ALTER TABLE "maclar" ADD FOREIGN KEY ("stadyum_id") REFERENCES "stadyumlar" ("id") ON DELETE SET NULL;

ALTER TABLE "dizilisler" ADD FOREIGN KEY ("mac_id") REFERENCES "maclar" ("id") ON DELETE CASCADE;

ALTER TABLE "dizilisler" ADD FOREIGN KEY ("takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;

ALTER TABLE "dizilisler" ADD FOREIGN KEY ("oyuncu_id") REFERENCES "oyuncular" ("id") ON DELETE CASCADE;

ALTER TABLE "olaylar" ADD FOREIGN KEY ("mac_id") REFERENCES "maclar" ("id") ON DELETE CASCADE;

ALTER TABLE "olaylar" ADD FOREIGN KEY ("oyuncu_id") REFERENCES "oyuncular" ("id") ON DELETE SET NULL;

ALTER TABLE "olaylar" ADD FOREIGN KEY ("takim_id") REFERENCES "takimlar" ("id") ON DELETE SET NULL;

ALTER TABLE "istatistikler" ADD FOREIGN KEY ("mac_id") REFERENCES "maclar" ("id") ON DELETE CASCADE;

ALTER TABLE "istatistikler" ADD FOREIGN KEY ("takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;

ALTER TABLE "istatistikler" ADD FOREIGN KEY ("oyuncu_id") REFERENCES "oyuncular" ("id") ON DELETE SET NULL;

ALTER TABLE "puan_durumu" ADD FOREIGN KEY ("yarisma_id") REFERENCES "karsilasmalar" ("id") ON DELETE CASCADE;

ALTER TABLE "puan_durumu" ADD FOREIGN KEY ("sezon_id") REFERENCES "sezonlar" ("id") ON DELETE CASCADE;

ALTER TABLE "puan_durumu" ADD FOREIGN KEY ("takim_id") REFERENCES "takimlar" ("id") ON DELETE CASCADE;
